export const memoryButtons = ["MC", "MR", "M+", "M-"];

export const scientificButtons = [
  "π",
  "e",
  "(",
  ")",
  "mod",
  "ANS",
];

export const mainButtons = [
  "C",
  "DEL",
  "%",
  "÷",
  "7",
  "8",
  "9",
  "×",
  "4",
  "5",
  "6",
  "−",
  "1",
  "2",
  "3",
  "+",
  "±",
  "0",
  ".",
  "=",
];

export const buttonTypes = {
  C: "danger",
  DEL: "danger",
  "=": "equals",

  MC: "memory",
  MR: "memory",
  "M+": "memory",
  "M-": "memory",

  "÷": "operator",
  "×": "operator",
  "−": "operator",
  "+": "operator",
  "%": "operator",
  mod: "operator",
  ANS: "operator",

  sin: "scientific",
  cos: "scientific",
  tan: "scientific",
  sec: "scientific",
  csc: "scientific",
  cot: "scientific",
  asin: "scientific",
  acos: "scientific",
  atan: "scientific",
  sinh: "scientific",
  cosh: "scientific",
  tanh: "scientific",
  ln: "scientific",
  log: "scientific",
  "√": "scientific",
  "x²": "scientific",
  "xʸ": "scientific",
  "10ˣ": "scientific",
  "1/x": "scientific",
  "|x|": "scientific",
  exp: "scientific",
  "n!": "scientific",
  floor: "scientific",
  ceil: "scientific",
  round: "scientific",
  random: "scientific",
  π: "scientific",
  e: "scientific",
  "(": "scientific",
  ")": "scientific",
};